# Runs on a schedule to check if the latest Gleam release is newer than the
# latest Chocolatey release. If it is, it will run the update script to update
# the Chocolatey package.

name: Automatic Release
on:
  workflow_dispatch:

jobs:
  publish:
    name: Publish new Version
    # needs:
    #   - update-files
    #   - check-versions
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Package
        run: choco pack

      # - name: Create Release
      #   uses: softprops/action-gh-release@v1
      #   with:
      #     body: Automatic Release from Github Actions for Gleam Release ${{ needs.check-versions.outputs.gleam-version }}
      #     tag_name: v${{ needs.check-versions.outputs.gleam-version }}
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     files: gleam.${{ needs.check-versions.outputs.gleam-version }}.nupkg

      - run: choco apikey --key ${{ secrets.CHOCO_KEY }} --source https://push.chocolatey.org/
        name: Login to Chocolatey

      - run: choco push --yes
        name: Publish to Chocolatey
