# Runs on a schedule to check if the latest Gleam release is newer than the
# latest Chocolatey release. If it is, it will run the update script to update
# the Chocolatey package.

name: Automatic Release
on:
  push:
    tags: ["v*"]

jobs:
  publish:
    name: Publish new Version
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - run: choco pack
        name: Package

      - uses: softprops/action-gh-release@v1
        name: Release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: gleam.${{ github.ref_name }}.nupkg

      - run: choco apikey --key ${{ secrets.CHOCO_KEY }} --source https://push.chocolatey.org/
        name: Login

      - run: choco push --yes --source https://push.chocolatey.org/
        name: Push
