# Runs on a schedule to check if the latest Gleam release is newer than the
# latest Chocolatey release. If it is, it will run the update script to update
# the Chocolatey package.

name: Automatic Release
on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  check-versions:
    name: Check Versions
    runs-on: ubuntu-latest
    outputs:
      should-run: ${{ steps.compare-version.outputs.satisfies }} == '>'
    steps:
      - id: gleam
        name: Get latest Gleam release
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: gleam-lang/gleam
      - id: chocolatey
        name: Get latest Gleam Chocolatey release
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: harryet/gleam-chocolatey
      - uses: web3j/substr-action@v1.2
        name: Strip Gleam 'v' version prefix
        id: strip-gleam
        with:
          value: ${{ steps.gleam.outputs.release }}
          start: '1'
      - uses: web3j/substr-action@v1.2
        name: Strip Chocolatey 'v' version prefix
        id: strip-choco
        with:
          value: ${{ steps.chocolatey.outputs.release }}
          start: '1'
      - id: compare-version
        uses: madhead/semver-utils@latest
        with:
          version: ${{ steps.strip-choco.outputs.result }}
          compare-to: ${{ steps.strip-gleam.outputs.result }}
      - id: test
        run: |
          echo "${{ steps.compare-version.outputs.release }}"
          echo "${{ steps.compare-version.outputs.major }}"
          echo "${{ steps.compare-version.outputs.minor }}"
          echo "${{ steps.compare-version.outputs.patch }}"
          echo "${{ steps.compare-version.outputs.build }}"
          echo "${{ steps.compare-version.outputs.build-parts }}"
          echo "${{ steps.compare-version.outputs.build-0 }}"
          echo "${{ steps.compare-version.outputs.build-1 }}"
          echo "${{ steps.compare-version.outputs.comparison-result }}"
          echo "${{ steps.compare-version.outputs.satisfies }}"
          echo "${{ steps.compare-version.outputs.inc-major }}"
          echo "${{ steps.compare-version.outputs.inc-premajor }}"
          echo "${{ steps.compare-version.outputs.inc-minor }}"
          echo "${{ steps.compare-version.outputs.inc-preminor }}"
          echo "${{ steps.compare-version.outputs.inc-patch }}"
          echo "${{ steps.compare-version.outputs.inc-prepatch }}"
          echo "${{ steps.compare-version.outputs.inc-prerelease }}"
      - id: print-comparison
        name: Print Comparison
        run: |
          echo "Gleam Version: ${{ steps.strip-gleam.outputs.result }}"
          echo "Choco Version: ${{ steps.strip-choco.outputs.result }}"
          echo "Comparison: ${{ steps.version.outputs.comparison-result }}"
          echo "Will Update: ${{ steps.compare-version.outputs.satisfies == '>' }}"

  update:
    name: Update Gleam Chocolatey
    needs: check-versions
    if: needs.check-versions.outputs.should-run == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Update
        run: |
          echo "TODO: Run update here!"
