# Runs on a schedule to check if the latest Gleam release is newer than the
# latest Chocolatey release. If it is, it will run the update script to update
# the Chocolatey package.

name: Automatic Release
on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  check-versions:
    name: Check Versions
    runs-on: ubuntu-latest
    outputs:
      should-run: ${{ steps.compare-version.outputs.satisfies }} == '>'
    steps:
      - id: gleam
        name: Get latest Gleam release
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: gleam-lang/gleam
      - id: chocolatey
        name: Get latest Gleam Chocolatey release
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: harryet/gleam-chocolatey
      - uses: web3j/substr-action@v1.2
        name: Strip Gleam 'v' version prefix
        id: strip-gleam
        with:
          value: ${{ steps.gleam.outputs.release }}
          start: '2'
      - uses: web3j/substr-action@v1.2
        name: Strip Chocolatey 'v' version prefix
        id: strip-choco
        with:
          value: ${{ steps.chocolatey.outputs.release }}
          start: '2'
      - id: compare-version
        uses: madhead/semver-utils@latest
        with:
          version: ${{ steps.strip-choco.outputs.substring }}
          compare-to: ${{ steps.strip-gleam.outputs.substring }}
      - id: print-comparison
        name: Print Comparison
        run: |
          echo "Gleam Version: ${{ steps.strip-gleam.outputs.substring }}"
          echo "Choco Version: ${{ steps.strip-choco.outputs.substring }}"
          echo "Comparison: ${{ steps.version.outputs.comparison-result }}"
          echo "Will Update: ${{ steps.compare-version.outputs.satisfies == '>' }}"

  update:
    name: Update Gleam Chocolatey
    needs: check-versions
    if: needs.check-versions.outputs.should-run == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Update
        run: |
          echo "TODO: Run update here!"
