# Runs on a schedule to check if the latest Gleam release is newer than the
# latest Chocolatey release. If it is, it will run the update script to update
# the Chocolatey package.

name: Automatic Release
on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  check-versions:
    name: Check Versions
    runs-on: ubuntu-latest
    outputs:
      should-run: ${{ steps.compare-version.outputs.satisfies == '<' }}
      gleam-release: ${{ steps.gleam.outputs.release }}
    steps:
      - id: gleam-release
        name: Get latest Gleam release
        uses: actions/github-script@v6
        with:
          script: |
            return github.rest.repos.getLatestRelease({
              owner: "gleam-lang",
              repo: "gleam",
            });
      - id: chocolatey-release
        name: Get latest Gleam Chocolatey release
        uses: actions/github-script@v6
        with:
          script: |
            return github.rest.repos.getLatestRelease({
              owner: "harryet",
              repo: "gleam-chocolatey",
            });
      - uses: web3j/substr-action@v1.2
        name: Strip Gleam 'v' version prefix
        id: strip-gleam
        with:
          value: ${{ steps.gleam-release.outputs.release.name }}
          start: '1'
      - uses: web3j/substr-action@v1.2
        name: Strip Chocolatey 'v' version prefix
        id: strip-choco
        with:
          value: ${{ steps.chocolatey-release.outputs.release.name }}
          start: '1'
      - id: compare-version
        uses: madhead/semver-utils@latest
        with:
          version: ${{ steps.strip-choco.outputs.result }}
          compare-to: ${{ steps.strip-gleam.outputs.result }}
      - id: print-comparison
        name: Print Comparison
        run: |
          echo "Gleam Version: ${{ steps.strip-gleam.outputs.result }}"
          echo "Choco Version: ${{ steps.strip-choco.outputs.result }}"
          echo "Comparison: ${{ steps.compare-version.outputs.comparison-result }}"
          echo "Will Update: ${{ steps.compare-version.outputs.comparison-result == '<' }}"

  update:
    name: Update Gleam Chocolatey
    needs:
      - check-versions
    if: needs.check-versions.outputs.should-run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - id: fetch-release-sha
        name: Fetch release SHA
        run: |
          curl -o ./release.zip.sha512 -LJO https://github.com/gleam-lang/gleam/releases/download/${{ needs.check-versions.outputs.gleam-version }}/gleam-${{ needs.check-versions.outputs.gleam-version }}-x86_64-pc-windows-msvc.zip.sha512
          export SHA_FILE=$(cat ./release.zip.sha512)
          echo "sha=${SHA_FILE:0:128}" >> $GITHUB_OUTPUT
      - id: clean-last-version
        run: |
          rm ./gleam-chocolatey.nuspec
          rm ./tools/chocolateyinstall.ps1
      - id: render-templates
        name: Render templates
        uses: pedrolamas/handlebars-action@v2.1.0
        with:
          files: '**/*.handlebars'
          output-filename: '{{ file.dir }}/{{ file.name }}'
          delete-input-file: false
          html-escape: false
          dry-run: false
        env:
          VERSION: ${{ needs.check-versions.outputs.gleam-release.name }}
          SHA512: ${{ steps.fetch-release-sha.outputs.sha }}
          RELEASE_NOTES: ${{ needs.check-versions.outputs.gleam-release.body }}
      - id: print-files
        run: |
          cat ./gleam-chocolatey.nuspec
      - id: print-files-2
        run: |
          cat ./tools/chocolateyinstall.ps1
      # # Create release
      # - id: release
      #   name: Create Github Release
      # # Tidy repo to publish
      # - id: clear-repo
      #   name: Tidy Repo
      # # Choco publish
      # - id: publish
      #   name: Publish to Chocolatey
