name: update
on:
  push:
    tags: ["v*"]

jobs:
  update:
    name: Publish ${{ github.ref_name }}
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        name: Checkout

      - run: choco pack
        name: Package

      - uses: softprops/action-gh-release@v2
        name: Release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: gleam.${{ github.ref_name }}.nupkg

      - run: choco apikey --key ${{ secrets.CHOCO_KEY }} --source https://push.chocolatey.org/
        name: Login

      - run: choco push --yes --source https://push.chocolatey.org/
        name: Push
